### ISSUE TITLE
Next default engine for KaOS?

### ISSUE THREAD

**Issue by demmm** [KaOS-Community-Packages/kvantum#4]
@jomada Since you seem to maintain this package, do you think it will be a good replacement for qtcurve?  Create the next Midna theme based on Kvantum?  If so, then this will move to the regular repos.

**Comment by jomada** [comment]
@demmm It is a good replacement, it is active, with recent updates, I can take a theme as a base and adapt it to Midna

**Comment by demmm** [comment]
>I can take a theme as a base and adapt it to Midna

That would be great.  I'll start adding kvantum to the repo tomorrow.

**Comment by demmm** [comment]
With the above commit, kvantum will be removed from KCP once moved to the apps repo.

**Comment by jomada** [comment]
@demmm I have the Kvantum Midna and Midna Dark themes ready, where I send the link to the themes?

**Comment by demmm** [comment]
If you want to have the credit you deserve (staying up in git forever), fork the [midna](https://github.com/KaOSx/midna) repo, add your kvantum files to it and open a merge request.

**Comment by demmm** [comment]
Kvantum Midna files merged + needed cmake changes added:
https://github.com/KaOSx/midna/commit/01c0641cf23cc2cf7bae42ce363eaf8c2992af2b

Closing this issue now, and will remove the Kvantum package from KCP tomorrow.
